# Generated by Django 2.1.7 on 2019-02-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(default='None', max_length=32)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('insertDate', models.DateField(auto_now_add=True)),
                ('expirationDate', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Medicines',
            },
        ),
        migrations.CreateModel(
            name='Pharmaceutical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('medicalPrescription', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Pharmaceuticals',
            },
        ),
        migrations.CreateModel(
            name='Bandage',
            fields=[
                ('medicine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Medicine')),
                ('is_sterile', models.BooleanField(default=False)),
                ('openedDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bandages',
            },
            bases=('inventory.medicine',),
        ),
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('medicine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Medicine')),
            ],
            options={
                'verbose_name_plural': 'Pills',
            },
            bases=('inventory.medicine',),
        ),
        migrations.CreateModel(
            name='Syrup',
            fields=[
                ('medicine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Medicine')),
                ('openedDate', models.DateField(blank=True, null=True)),
                ('validity', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Syrups',
            },
            bases=('inventory.medicine',),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('medicine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Medicine')),
                ('is_sterile', models.BooleanField(default=False)),
                ('openedDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tools',
            },
            bases=('inventory.medicine',),
        ),
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Pharmaceutical'),
        ),
    ]
